version: '3.8'

services:
  php-apache-environment:
    working_dir: /app
    volumes:
      - ./src:/app
    image: olalekan:v1
    build:
        context: .
        dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:8080
    depends_on:
      - db
    links:
      - "db"

  # MySQL Database
  db:
    command: --default-authentication-plugin=mysql_native_password
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: csym019
      MYSQL_ROOT_PASSWORD: csym019
      MYSQL_DATABASE: recipe_db
    restart: "on-failure"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 5001:80
    depends_on:
      - db
    links:
      - "db"
